.github/workflows/gh-actions.yml
README.md
bibtex-actions.el

This adds mtreca's macro, etc.

Add command wrappers

---

README.md

This should cover the sort of bases that would be necessary either for this project, or if this was merged to bibtex-completion.

Fill out the basic README

---

bibtex-actions.el

Addresses #12.
If we go this direction, we could add back detail to the rest of the docstring.

Simplifying command names, docstrings

---

bibtex-actions.el

Make sure crm-separator overrides default

---

bibtex-actions.el

Still not sure, but this fixes #16.
I decided to just merge the two "read" function into the single now public function?
Thoughts before I merge?

refactor: merge read functions, make public

---

bibtex-actions.el

Improves the if check on links, and adds the symbol back.
If someone wants configurable prefixes, I'm not really interested in 
adding that myself, but would be open to a PR.

improve has-link

---

bibtex-actions.el

fix: field truncate-to-width on format-entry

---

bibtex-actions.el

This is a vestige of a PR no longer needed.

remove truncate function

---

test/install.el

- add elpa repo
- install and use 'load-relative'
- install 'bibtex-completions'

test(install.el): fix errors

---

bibtex-actions.el

autoload commands

---

.github/workflows/gh-actions.yml
README.org

While I'm at it, also restrict the GA workflow to only checking elisp files.

docs: add note on shared backend

---

README.org
test/bibtex-actions.el

Update the README and the test script.
Fix #173.

docs: Clarify search fields

---

README.org
test/bibtex-actions.el
test/install.el

Which-key isn't an ideal interface for embark-act, so remove it.

test: Remove which-key, update oc file name

---

bibtex-actions.el

While this definitely had its advantages, it was a hack.
This removes it, on the assumption better to have too many candidates
than too few.
Also, the excellent `consult-completing-read-multiple` doesn't play well with it; see https://github.com/bdarcus/bibtex-actions/issues/191#issuecomment-886273664.
cc @ilupin @titaniumbones @publicimageltd @apc @salutis

Remove initial input

---

README.org
bibtex-actions.el

Added filenotify based convenience functions and updated the README with example usage. They have been mildly tested in my personal config.
Also touched up comments a bit.

Filenotify convenience functions

---

oc-bibtex-actions.el

Using faces to different styles and variants is an experiment.
Still uncertain about whether I want to always highlight the style name; even if it has a variant attached to it.
For now I've decided no.

Add a face to style variants too

---

oc-bibtex-actions.el

- change preview-alist to a simple key-value
- uncomment annotation function again

Simplify preview, reactivate

---

README.org
bibtex-actions.el
oc-bibtex-actions.el

As we discussed on the last pr. I might messed up some git things.

(Hopefully) improved filenotify based refreshing

---

bibtex-actions.el

I think I have managed to refactor `bibtex-actiona--format-entry` into a form where it is easier to see what is happening.

Refactor bibtex-actiona--format-entry

---

README.org

Can you check these @denismaier @ebouna?
I haven't had much time to look at this closely, but this is an iteration of the example @denismaier came up with.
Should fix #209

fix use-package examples

---

bibtex-actions.el

Fix (not well) affixation alignment + a quoting issue

---

bibtex-actions.el

Use bibtex-actions--extract-keys.

fix: open-entry

---

bibtex-actions-file.el

Implement multiple parsers + add Calibre parser

---

README.org
bibtex-actions-file.el

Cleaning up #293.
First stab at addressing your comments @aikrahguzar.

refactor files- functions

---

bibtex-actions.el

Adapt run-default-action to keys-entries

---

CONTRIBUTING.org

It took me a while to figure this out on my own, so I thought it would
be helpful to have it documented somewhere.  README might be more
appropriate.

add brief documentation about function forms

---

oc-bibtex-actions.el

Change all keymaps from defvars to defcustoms and put them towards the
top to emphasize one can modify the behavior.

refactor(oc): change keymaps to defcustoms

---

bibtex-actions.el
oc-bibtex-actions.el

This doesn't appear to offer any real value.

remove bibtex-actions-describe-keymap

---

README.org

Typo in README.org

---

citar.el

remove kbs for obsolete commands

---

citar.el

* Having a complicated type for the `citar-major-mode-functions` defcustom was breaking the customize buffer. For now, just give it a simple alist type. Fixes #371.
* Improve the type specifications for various other defcustoms.
* Fix a typo in a keymap definition.
* Use derived-mode-p to test the keys in `citar-major-mode-functions`, and allow `t` as a key to serve as the fallback choice.

Fix defcustom types, and other small changes

---

citar-markdown.el
citar.el

This works, though not sure if it's the best code.

feat(markdown): citar-markdown-at-point

---

citar-file.el
citar.el

There's no real problem with adding this parser, so ...

add triplet parser to file parsers

---

citar-file.el

fix(file): dedup default file parser results

---

citar.el

Am not sure if this is really necessary, despite the short-term transition pains.
Fix #409

fix: add check that paths are lists

---

citar.el

feat: only prompt for files if more than one

---

citar.el

fix: only open selected files, in accordance with prompt

---

citar-file.el
citar.el

Add defcustom citar-note-extensions

---

README.org

As soon as the Doom PR is merged, I'll merge this.

docs: add note on Doom biblio module support

---

citar.el

When running `embark-act` in the minibuffer, the targets are formatted candidate strings rather than citation keys. Add an Embark target transformer that will convert these strings back into the easy-to-read citation keys.
Also merge together `citar-select-ref` and `citar-select-refs`, since they have lots of commonality. Now `citar-select-refs` is a small wrapper for `citar-select-ref`.
Fix #435, an issue with the handling of non-existent keys.

Embark target transformer

---

citar-org.el

Can you check if this fixes it @Yevgnen?
------
Fix #461.

fix: evil-state error

---

citar.el

Also remove citar-insert-citation from embark maps

Add citar-copy-reference to embark maps

---

citar-citeproc.el
citar-file.el
citar.el

Also fix some defcustom types to use 'directory where appropriate.

Update documentation of functions in `citar-file`

---

citar.el

`citar-file--make-file-predicate` should be `citar-file--has-file`.

Fix bug in #482.

---

citar-file.el

Close #488
--------
WDYT @roshanshariff @localauthor?

Add optional ext arg to parse-file-field

---

citar.el

When running `embark-act` on multi-key citations, the target string is of the form "key1 & key2 & key3". Fix `citar--extract-keys` and `citar--ensure-entries` to correctly handle KEYS-ENTRIES lists containing strings of this form.

Correctly handle `embark-act` on multi-key citations (fix bug in #487)

---

citar.el

I see no issue with merging this @roshanshariff, but let me know ....
------------
Close #497

Use seq-remove in place of cl-delete-if

---

citar.el

Fix #508
May also re-implement #491 if I can find the time.

fix: type error

---

citar.el

Working on #491 on this new branch.
Just need to adapt https://github.com/bdarcus/citar/pull/491#issuecomment-1001700408, as `embark-act-all` isn't currently working.

Use consult-multi for citar-open, include notes

---

citar-file.el
citar.el

per comment in this thread:
https://github.com/bdarcus/citar/pull/513#discussion_r776470085

fixes to multi-category implementation

---

citar.el

Per suggestion here: https://github.com/bdarcus/citar/pull/514#discussion_r776857405

Use 'propertize' instead of 'add-text-properties'

---

citar.el

Add error to citar-get-template

---

citar-latex.el

When inserting keys into an existing citation, improve the handling of cases like `\cite{key,key2,}` (with an extra comma).  Now adds a comma only if necessary to insert new keys into the desired position.
Fix #533.

citar-latex-insert-citation: improve editing of existing citations

---

citar-org.el

Change bindings on org buffer map

---

citar-filenotify.el
citar-latex.el

Fix #567.
@aikrahguzar - any feedback on this, including the docstring?
cc @gkowzan

File notify tweaks

---

citar.el

This is an alternative to #540, which keeps the current template format.
I still need to test more thoroughly.
Also, need to replace `s-match-strings-all` with a built-in in order to remove the s dependency. But initial checks there is no such thing, so would need to add another function here, and/or change how `citar--fields-for-format` works.
https://github.com/magnars/s.el/blob/08661efb075d1c6b4fa812184c1e5e90c08795a9/s.el#L452
Thanks to @aikrahguzar, who I credited on the commit.
Close #335.

Remove s dependency

---

citar-org.el

Need to add this argument so that prefix arg in org-cite-insert will
work correctly.
Close #572

oc: add optional prefix arg to select style

---

citar.el

Needs more testing with local bibs, but this seems to work fine, and results in simpler and clearer code.
I'll plan to merge this tomorrow (May 8), since this does fix an obvious bug with embark collect buffers.
cc @roshanshariff 
-------------------
Make sure `embark-act-all` works from an Embark Collect buffer.
Close #583

Fix embark transformer

---

citar.el

Replace the original pdf-oriented function with a more general one.
Close #528
--------
This currently assumes one file per key.
If a file already exists, Emacs will prompt to confirm whether you want to overwrite it.
I'm thinking it also might confirm the file name/path before saving?
But can worry about those later, I think.

Add citar-add-file-to-library

---

citar.el

This more or less reproduces the usual ui without needing `completing-read-multiple` including `TAB` and `RET`. With a little convoluted logic vertico works out of the box without depending on it. We just rely on the fact that `exit-minibuffer` is remapped to `vertico-exit` on the `vertico-map` so any other ui that does this remapping will work out too.
Embark works for actions on single references but I haven't added the function which allows `embark-act-all` to work with the selected-candidates. I think it should work but I don't really know how to test it.

Rework multiple selection to use completing read in a loop

---

citar.el

Lemme know if this is what you had in mind. I didn't make any changes to the README -- I figured you would want to do that.

Add citar-capf

---

citar-capf.el

Followup to #629.
I decided to base this on main, as it's trivial to adjust it for the new branch, and I don't want to run into git history problems.
So I think just need to settle the exit function on the defvar. Maybe need to wrap it in a lambda?

citar-capf follow-up

---

citar.el

Embark inserts the target as text read from the minibuffer when acting on interactive commands (that are not multi-target actions). For `citar-reference` targets, this text is a citation key rather than a formatted candidate. To support this, `citar-select-refs` now treats any text returned by `completing-read` as a citation key when it is not a valid candidate.
Fixes #655.

Allow `citar-select-refs` to be used with `embark-act`

---

citar.el

Prompt for extension if needed; handle some other potential errors.

Minor refactor of `citar-add-file-to-library`

---

citar.el

Fix #644
------
This closes I think the remaining issue for 1.0.
@roshanshariff - aside from adding this, I fixed a couple of docstring issues; you might want to just confirm, but I think I got it right. For example, there was mention of `:multiple` on `citar-select-ref`, but there is no longer such an argument, and it doesn't make sense when you set it `nil` anyway.

Regeneralize citar-open-entry

---

citar.el

Add binding hint to multi UI

---

citar.el

Fix linter warnings on indentation and long docstring lines.

---

citar.el

See #703.
I confess I actually forget what `:transform` does! @roshanshariff?

Clarify notes API docstrings

---

citar-capf.el

Change the capf so completion is on the citekey, and add an annotation.
Close #660
------
IUC (and it's possible I don't), this addresses the limitations that @roshanshariff noted [here](https://github.com/emacs-citar/citar/issues/660#issuecomment-1419377554), and that @mclearc referenced.
The candidates are drawn from `citar-get-entries`.
I'm not 100% sure on the UX (completing on citekeys), though my hunch is this makes more sense.

capf: Refactor to complete on key, use cache

---

citar.el

A simple PR to implement #736.

Make `citar-open-entry` configurable

---

README.org

Doom emacs has switched from develop to master branch.

Update Doom docs link

---

README.org

Mentioned in https://github.com/emacs-citar/citar/issues/791

Explicitly recommend order-independent completion style

---

citar.el

Add options to customize citar-add-file-to-library

---

citar-latex.el

fix(latex): avoid mutating reftex state
