bibtex-actions.el

Bibtex-completion has one function that uses the uppercase "PDF".
This change modifies the macro to downcase all command names.
Closes #4

Downcase new command names

---

bibtex-actions.el

To allow us to diverge from some of the bibtex-completion function names, this modifies the macro to accept an optional parameter that defines the command name explicitly.
To wit, it also changes a few of the names for concision and consistency.

Modify macro to accept optional name argument

---

bibtex-actions.el

As I started to work on this, I just decided to remove the macro, in favor of explicit defuns.
This not only makes it easy for us to diverge from bibtex-completion naming (already possible with an earlier change), but makes it all more simple and clear.
And adding new action functions specific to this package (I'm not sure what they might be, but I can imagine will come up) would be consistent.
It's also (slightly) less code.
Not sure about some of the parameters and docstrings though.
Closes #14.

refactor: Remove macro and require explicit defuns

---

bibtex-actions.el

The bibtex-completion functions all take multiple keys as input, and
some of them (notably the "input" ones) lose functionality without
support for this.
Hence, this changes the core read function to use
'completing-read-multiple'.
In order to do that, it also sets the `crm-separator` to ampersand, since 
default comma won't work for these data.
Addresses #17.
see https://github.com/oantolin/embark/issues/176#issuecomment-794597585

Change to completing-read-multiple

---

bibtex-actions.el

This changes mapcar to cl-loop in main read function for consistency, 
speed, and because it's a little more clear to me.

refactor: change mapcar to cl-loop

---

bibtex-actions.el

Something I did with #37 broke crm multi-selection of candidates.
I have narrowed it down to the changes I made to `bibtex-actions--get-candidates`. It's probably something obvious, but I can't see it ATM!
This code now works correctly, but removes the feature I wanted from the offending code: add the pdf/link/note strings to the candidate.
EDIT: an idea: it would be the whitespace I ended up introducing at the end of the candidate strings?
cc @mohkale

fix for #39

---

bibtex-actions.el

Add suffix UI, using the same configuration method as for the main display formatting.
Also add annotation-function, to provide the same UI pre-Emacs 28..
To enable this, I have adapted some code from bibtex-completion. I will 
that code, or greatly simplify it, if and when this PR is merged:
https://github.com/tmalsburg/helm-bibtex/pull/367
Closes #44
------
Here's what it looks like now, with these two PRs, and configured to use `all-the-icons`:

feature(ui): add suffix 

---

bibtex-actions.el

As a general rule, when messing with the candidate strings, one must 
right trim, to remove trailing whitespace.
This ensures that multi candidate selection will work correctly with crm.
Fixes #52

trim-right candidate string

---

bibtex-actions.el

In theory, a user can now configure the candidate strings in such a way
that, with certain records, candidates may not be unique. This ensures
that doesn't happen.
Also, remove (now) superfluous 's-trim-right' on 'candidate-invisible' 
variable.
fix #55

add citekey to invisible candidate string

---

bibtex-actions.el

Since the completion candidates now use the same string for search and for
display, rename the templates and update the docstrings to avoid any
confusion.

refactor: '-display-template' -> '-template'

---

.gitignore
bibtex-actions.el

This initially started based on a misunderstanding of the `candidates` variable in the `bibtex-actions-read` function.
Given that the candidates are refreshed each time the function is run, instead go the opposite direction: remove any of this file-notify-based logic.
Can always revisit later if need be.

remove bibtex-completion-init call

---

bibtex-actions.el

With the addition of the suffix template, candidates were extending 
beyond the frame, which causes rendering oddness in some completion 
systems.
This fixes that, though does so currently using fixed ratios.

adjust widths to accommodate two sections

---

README.md
bibtex-actions.el

Refactor so that  `bibtex-actions-read` pulls candidates from a 
cache: `bibtex-actions--candidates-cache`.
Add:
- `bibtex-actions--candidates-cache` variable
- `bibtex-actions-refresh` interactive command, to update cache
Refactor:
-  `bibtex-actions--get-candidates` renamed to `bibtex-actions--format-candidates`
-  `bibtex-actions--get-candidates` now grabs the candidates from the cache
fixes #69
-----
@wenjie2wang - I do think it would also be good to add the hook to bibtex-completion, but you want to give this a try and let me know?
Turns out it was easier than I thought to add this.
But I haven't fully tested it and seen if it has any unintended consequences.
It does cache the candidates, however, so should address #69.
So if you could test it further and let me know, that'd be …

refactor: add candidates cache

---

README.md
bibtex-actions.el

Update `bibtex-actions-refresh` to allow it be invoked as a callback on `file-notify-add-watch` without requiring a lambda.
Also update the README to incorporate the change.
Relates to #73.

refactor: add optional parameter to refresh command, update docs

---

bibtex-actions.el

This fixes so that the template processing function is only called once,
rather than every time the format-entry function runs.

refactor: move template processing

---

bibtex-actions.el

This fixes a couple of dumb, though harmless, bugs.
In theory, this will improve performance of `bibtex-actions--format-candidates`.

refactor: move general format vars out of loop

---

test/install.el

Instead of installing the `bibtex-actions` package from MELPA, now loads 
it locally.
This allows it to work for both users kicking the tires, and for 
developers wanting to run against a local branch.
Simple fix for #98.

test: load local bibtex-actions.el on script

---

README.org

It seems that there are some typos on `bibtex-actions-template` in the `README.org`.  This PR fixes those typos.

fix typos in readme

---

README.org

To make it easier to track diffs going forward, this converts the README to use "one sentence per line" formatting.

docs (readme): change format to ospl

---

bibtex-actions.el

@apc - here's the start on #116.
It allows `bibtex-actions-read` to be called like this:
``` elisp
(bibtex-actions-read :initial "has:pdf")
```
So I changed the read function to include the `:initial` parameter, and also added the "initial-value" arguments to the relevant open commands.

Add filtering on open commands

---

README.org
bibtex-actions.el

This adds history support.
It also may address #119, per suggestion from @oantolin in https://github.com/bdarcus/bibtex-actions/issues/119#issuecomment-828810012.
> ... you can just prepopulate the history with the predefined searches, and people can use a command to search history with completion such as `consult-history`.
Two questions, @oantolin:
First, to "prepopulate the history", Is it really so simple as the below?
``` elisp
(setq bibtex-actions-history '("analysis" "chem"))
```
Second, how to activate the history?
If I run `consult-history`, for example, in any random buffer, I get a "no history configured" for that mode error.
Would this be something where I would just need to turn it on, for say, `text-mode`?? If yes, how? And in this package, or in a suggested README config?

add bibtex-actions-history

---

README.org
bibtex-actions.el

For all interactive functions, pass the prefix to `bibtex-read' to
allow optionally enforcing the reloading of the bibliography cache.
This is to avoid having to call `bibtex-actions-refresh` manually if the library file has been changed.

Add prefix argument to force reloading of the cache

---

bibtex-actions.el

The default value on `bibtex-actions-open` was defined as:
```
has:pdf\|has:link
```
... but was inserted without the escape backslash.
This fixes that.

fix: escape bug on regex

---

bibtex-actions.el

This adds a hook which is run when reloading is forced by pressing C-u.
Note that this hook is not run in a usual refresh, since recreating a bibliography file can take a while and thus should be explicitly requested. Here's my setup, using the function `pullbib-pull` to create the bibliography file on demand:
```emacs-lisp
(setq bibtex-actions-force-refresh-hook  (list #'pullbib-pull))
```

Add hook for force reloading

---

bibtex-actions.el

Declare `crm-separator` for byte compilation to avoid lexical/dynamic binding issue (see #126).

Add compiler declaration of crm-separator

---

README.org
bibtex-actions.el

Here's the PR for the customizable initial input. AFAIU, all other occurences of strings like "has:pdf" in the source code are used for actually inserting these strings in the candidates, so they should not be affected by that change.
Closes #129.

Customize initial input

---

bibtex-actions.el

It looks like `org-cite` is close to merging.
https://lists.gnu.org/archive/html/emacs-orgmode/2021-04/msg00790.html
So this implements a function to format that syntax.
You can use this init file to test this with the org-cite branch code:
https://gist.github.com/bdarcus/2645f99363fc47ddab2aae24c5d9e66c
Here's what the style prompt looks like:
... with results when inserting into the `new-org-cite` org branch:
Bibtex-completion has flexible citation formatting functions.
Here is the default currently:
``` elisp
(defcustom bibtex-completion-format-citation-functions
'((org-mode      . bibtex-completion-format-citation-ebib)
```
So this will hopefully replace `bibtex-completion-format-citation-ebib` as default.
I adapted this from the pandoc function, compared to which I have:
1. changed …

Add org-cite function

---

bibtex-actions.el

This PR allows the bibtex key at point as initial input. Actions are available through `bibtex-actions-at-point` with `bibtex-actions-open` as the default.

Add bibtex-actions-at-point

---

bibtex-actions.el

Allows `bibtex-completions-at-point` to work with `org-cite`.
Are you OK with me adding this on your behalf, @ilupin?
Though it might be better to see if you can get it accepted to `bibtex-completion`?
cc @tmalsburg

Add bibtex-actions-get-key-org-cite

---

README.org
bibtex-actions.el

This PR enhances `embark` support for `bibtex-actions-at-point`, which is inspired by the discussion in #142 and the [code](https://github.com/bdarcus/bibtex-actions/pull/137#issuecomment-857456998) presented by @publicimageltd.
If `embark` is installed, `bibtex-actions-at-point` will call `embark-dwim` (the default) or `embark-act`, depending on the option `bibtex-actions-embark-dwim`, when one or more citation keys are found at point, where `embark-dwim` runs the default action and `embark-act` prompts the user for an action in `bibtex-actions-embark-map`. If no key is found, `bibtex-actions-read` is used for choosing entries, and functions in `bibtex-actions-map` can still be called via `embark-act`.
This PR uses `bibtex-actions-get-key-org-cite` and `bibtex-completion-key-at-point` to …

Add `embark` support for citation keys at point

---

bibtex-actions.el

Add a complete-at-point function, to complement `bibtex-actions-insert-citation`, targeting `org-cite`.
Some users may find this more efficient, in some cases. And we use the same candidates.
Basic completion works, with this the UI I'm looking for ...
Current status is outlined here: https://github.com/bdarcus/bibtex-actions/pull/132#discussion_r656325631.
Aside: I did make a recommendation to include this in `org-cite` directly, though I imagine that may not get support. My idea was just to allow the candidates list to be configurable, so that using it with `bibtex-actions` would just involve something like:
``` elisp
(setq org-cite-capf-candidates (bibtex-actions--get-candidates))
```
See #91.

Add bibtex-actions-complete-key-at-point

---

bibtex-actions.el

Needs more testing, and documentation, but this wraps `bibtex-actions-at-point` to provide an `org-cite` "follow processor".
If you do ...
``` elisp
(setq org-cite-follow 'bibtex-actions)
```
... and then `C-c C-o` on a citation or citation-reference at point, it will run `bibtex-actions-at-point`.
Closes #141
cc @ilupin

feat,oc: Add follow processor

---

README.org
bibtex-actions.el

Makes `bibtex-actions-read` available as an "insert processor".
``` elisp
(setq org-cite-insert-processor 'bibtex-actions)
```

Add oc-insert processor

---

README.org
bibtex-actions.el
test/bibtex-actions.el

This fixes the initial embark at-point integration.
With this PR, default behavior when point is on an `org-cite` citation or citation-reference:
- `M-x org-open-at-point` -> `embark-dwim` (the default action)
- `embark-act` presents bibtex-actions command options
Both `embark-act` and `embark-dwim` should also correctly work in `latex-mode`.
Please test and confirm this is all working as expected, including the minibuffer commands and `embark-act` behavior.
Also, I've updated the test script to show the `org-cite` capabilities.
Fix #164.

fix embark at-point

---

bibtex-actions.el

if `bibtex-completion-cite-prompt-for-optional-arguments` is nil, set `style` to "default" before inserting citation string.
fixes #162

ensure `style` is set in bibtex-actions--format-citation-org

---

README.org
bibtex-actions-org-cite.el
bibtex-actions.el
test/bibtex-actions.el
test/install.el

I've decided to move org-cite specific stuff into a separate `bibtex-actions-org-cite`. We can start with this, and expand it as needed, including possibly later considering a minor mode and such.
It reflects where I ended up, where I was finding it difficult to fix the problem with the insert processor that @ilupin [discovered](https://github.com/bdarcus/bibtex-actions/pull/171#issuecomment-877738027), and it seemed easier to split out the org-cite stuff into a separate `bibtex-actions-org-cite` file, and remove the `with-eval-after-load` embark config from the main file.
I think this is the right approach, but could use some more review and testing.
You should just be able to load the file and it will work with `org-cite` (assuming you have that properly setup).
Note also I am …

Add separate bibtex-actions-org-cite

---

bibtex-actions-org-cite.el
bibtex-actions.el

This is @minad's suggestion: https://github.com/bdarcus/bibtex-actions/pull/171#discussion_r667755127
Edit: actually, I integrated a part of that suggestion in #174. This just refines it.

oc: Use bibtex-actions-at-point-function for follow processor

---

README.org

This updates the README to offer three config options to best match recent org-cite/embark-related enhancements:
1. basic
2. embark (embark, but works the same across markdown, latex, org)
3. org-cite (same as 2, but has custom menus and commands for org-cite)
I can then work backward from there; tweak code to match what we want in the `use-package` statements.
In particular, a key question: what's the best way to deal with the fact that org-cite-related functionality depends on Org 9.5?
Aside: `(featurep 'oc)` will test for presence of `org-cite`.
Right now, I put all of that in [`bibtex-actions-org-cite.el`](https://github.com/bdarcus/bibtex-actions/blob/main/bibtex-actions-org-cite.el).
But should I move the functions on which org-cite functionality depends back into the main package …

Update use-package examples

---

bibtex-actions.el

Add a primary candidate face, and a "highlight" one; the former would replace the previous "suffix" one.
Key question is just what parent faces to reference.
A few theme examples:
Thoughts?

Add face, modify existing face

---

README.org

The readme and use-package example in it mention `bibtex-actions-org-cite`, but it seems that the currently provided name is `oc-bibtex-actions`, so I fixed it.

Use correct oc-bibtex-actions package name in documentation

---

oc-bibtex-actions.el

The in-buffer 'embark-act' command for inserting a citation runs
'org-cite-insert'.  But that command needs to run without argument.
This adds that command to a list of commands where Embark will ignore
that target input.

oc: fix 'embark-act' at-point insert citation

---

README.org
bibtex-actions.el

This adds support for local bib files, by adding a buffer-local cache.
When visiting a buffer, you should get the correct mix of local and global bib files loaded automatically.
Also adds a hidden `is:local` string to local candidates, so that you can filter local items like so:
Open questions:
1. Should local candidates already included in the global cache be removed from the local cache?
2. ~Best options for auto-freshing of cache so users don't have to think about this? Maybe we include an [example auto-timer hook](https://github.com/bdarcus/bibtex-actions/pull/208#issuecomment-892589239) in the README?~ settled; working on this
3. Should there be some kind of UI hint for local candidates, building on the above filtering? We discuss below grouping as one option, but there are more …

support local bibs

---

bibtex-actions.el
oc-bibtex-actions.el

This is a minimal alternative to #199.
The following works in org-cite:
- `M-x bibtex-actions-dwim`
- `M-x embark-dwim`
- `M-x org-open-at-point`
The only thing that doesn't work (for me at least):
- `embark-act` -> `RET` 
I do now get this message when clicking on a key, though, which might be a hint:
```console
Embark: The action indicator takes three arguments, KEYMAP, TARGET and TYPE.
```
If we can't get this working, I'll just remove that binding, which isn't that useful anyway.
Fix #195.
cc @ilupin

Fix embark-act > RET

---

oc-bibtex-actions.el

This static approach is still not ideal, but it does have certain advantages.
- fill out csl preview content
- change to csl as default style preview

feat(oc,style): switch to csl preview

---

README.org
oc-bibtex-actions.el

Generate style candidates via `org-cite-supported-styles`, and for the
time being, comments out the annotation-function.
Also:
- add section on styles to the README
- removing sorting on group-function

Generate style list dynamically

---

bibtex-actions-utils.el
bibtex-actions.el

bibtex-actions--process-display-formats refactor is exactly as before but refactored. 
Misc filenotify improvements, mostly that only the cache that is invalidated is recomputed when offering candidates.

bibtex-actions--process-display-formats refactor + filenotify improvements

---

bibtex-actions.el

This turned out to be straightforward.
This is what `(bibtex-actions--fields-to-parse)` produces with default templates,
```elisp
("author" "date" "title" "=key=" "=type=" "tags" "doi" "url" "file" "year" "issued" "id" "type" "keywords" "keyword")
```
Fix #231

Limit fields being parsed.

---

bibtex-actions.el

I had though that invisible strings were not displayed but still occupied space. But I was wrong. Reducing the star-width by 1 fixes the appearance of overflow indicator as least for me.
My best pr yet :)

Fix the overflow

---

bibtex-actions.el

Fixes #222 
It was caused by change of consing the whole candidate with the candidate string instead of just the key.
I don't see a downside of just assuming that the string is a literal key if it is not the display string of a candidate and just passing it on.

Fix passing literal keys

---

bibtex-actions-file.el

I made a mistake and pushed the initial commit to the main branch (sigh), but it was intended to go here.
So I'll finish it on this branch.
I'm not actually sure how best to do this with the template, but it's intended to be a simple thing, which is never-the-less compatible with `org-roam v2`.
Current code results in duplicate titles properties at the beginning, which is a Doom thing, so I can ignore that:
https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/file-templates/README.org
FWIW, here's what inserting a note using the default capture template in `org-roam v2` looks like:
So only real difference currently is it includes the property drawer for the file, and an org id.
But it should be easy enough to write, or borrow, an OR function for this.
Fix #239
Just FYI …

Add basic template for default note fn

---

bibtex-actions.el

For #237 
Mostly removes a lot of code.
`bibtex-actions-template` has a new type, so that might lead to type errors in a long session. 
Preferably test in a new session if everything works. Everything seems to work fine for me.

New layout for cached strings and overhaul of templates and formatting

---

bibtex-actions-file.el

Should fix #242 
It was result for `bibtex-actions-get-value` accepting a list of fields now. I checked the main file but not the other ones. I have now and it seems it was the only remaining usage not fixed.

Adjust use of ba-get-value default notes function

---

bibtex-actions-file.el
bibtex-actions.el

First one is an experiment I am not too sure about. I was a bit bothered about the fact that the shortening of author and editor names is a special case. So I created a `defcustom` that controls transforming the fields from the raw parsed string to one for display and now name shortening goes through it. I like the uniformity but not sure if it anyone would want to do something with it. 
As a related change `bibtex-actions-get-value` is back to accepting a single field. There are now two related functions, `bibtex-action-has-a-value` which accepts a list of fields and returns the first field for which the item has a value and `bibtex-actions-display-value` which accpets also accepts a list of fields and returns the display string. 
I also managed to find a more robust solution for …

Customizable field display + better fix for symbol alignment

---

bibtex-actions-file.el
bibtex-actions.el

Initial commit implement #229 as a simple flat list of related resources.
Still need:
1. ~add links~
2. `bibtex-actions-select-file`? 
3. probably also add a `consult--multi` option if present, rather than requiring consult; alternately, perhaps a better first step is to just add an annotation function to the simple flat version
If the latter, the annotation could just be types:
- DOI
- URL
- note
- file
...?

refactor bibtex-actions-open

---

bibtex-actions.el

'string-match' was only introduced in Emacs 28.

string-search -> string-match

---

README.org
bibtex-actions-file.el
bibtex-actions.el

Per #269, this adds a template for formatting new note titles, and a function to handle it.
It has occurred to me maybe this function should be called `format-entry`, and the original one renamed `format-entry-columns`?
Note: there's a [little change](https://github.com/bdarcus/bibtex-actions/pull/274/commits/6ddbe996b6d6d3c6b75379ac0ad7e80caa5b0c92#diff-43b58707c1adce5c6f3e1ed8d97ea5665182d94767472f7c196d630ff3ca0c3cL452) I made here that exposed a much bigger infinite recursion bug that I can't figure out how to fix otherwise.
```elisp
ELISP> (bibtex-actions--format-candidates bibtex-actions-bibliography)
*** Eval error ***  Lisp nesting exceeds ‘max-lisp-eval-depth’
```
Backtrace:
```elisp
Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
#<subr …
```

feat: add new format-entry function, note template

---

oc-bibtex-actions.el

Tried out the branch and it fetching data doesn't seem to get stuck anymore. But something like this was needed for `oc-bibtex-actions-insert` to work. Maybe this is not what is intended.

Adapt oc-bibtex-actions-insert to changed format

---

README.org
bibtex-actions-file.el
bibtex-actions.el
oc-bibtex-actions.el

This is fundamentally to fix #286 (a recursion bug), but may have other benefits for modularity and performance.
1. change `bibtex-actions-select-keys` to `bibtex-actions-select-refs`, which now returns `(key . entry)`
2. change functions that rely on keys to accept this richer input instead
3. decouple action and formatting functions from caches (no more looking up data there, which caused the bug)
See:
https://github.com/bdarcus/bibtex-actions/pull/274#issuecomment-917413257
This seems to fix it @aikrahguzar, but I need to test more.
Also, maybe need to change the function names.

fix: change functions to take entry, decouple cache from formatting

---

README.org
bibtex-actions-file.el
bibtex-actions.el

Better aligns with org-roam-bibtex.
See https://github.com/org-roam/org-roam-bibtex/pull/212

refactor: notes fn to take KEY and ENTRY args

---

README.org
bibtex-actions-file.el
bibtex-actions.el

Fix #282, #273; see also #226 and #229
cc @pRot0ta1p @salutis
I've implemented changes here to `bibtex-actions-open-library-files` and `bibtex-actions-open` interactive functions, and related defcustoms.
So to configure flie handling, you can do this:
```elisp
(setq bibtex-actions-file-extensions '("org" "md" "pdf") ; open with the default open command; find-file
bibtex-actions-file-extensions-external '("mp3" "png" "tiff" "html"))
```
WDYT? 
TODO:
1. need to make sure this works correctly with file-fields
Aside: occurs to me HTML may be a little tricky, because we pretty much only want to view these files; not edit them. But some may want to view in emacs.

open file refinements

---

README.org
bibtex-actions-file.el

1. rename the zotero parser to default
2. add a semi-colon option to the calibre parser, rename it
Is this OK @thisirs?
@pRot0ta1p - isn't this the only change needed?
Assuming yes, what's a better name for the "calibre" parser, since it's now broader? Here's I've renamed it to "triplet".
Also, do you know if semi-colon is consistently used as the delimiter for this simpler syntax? 
Fix #296

refactor file parsers and broaden syntax support

---

bibtex-actions-file.el

Fix #311
@dschrempf - can you give this a try and see what you think? If you have the note template set to `nil`, it opens a blank document.
I'm not sure it's the best general solution, but it's simple enough.

If note template nil, don't insert content

---

oc-bibtex-actions.el

This adapts some of the functions from org-ref-cite (whose future is now unclear) for modifying citations.
The delete-citation and kill are simple no-brainers.
The "shift" ones seem useful to me, and would ideally work the same as in org-ref-cite; they'd be attached via keymap face, so one could use arrow keys. 
Not sure what else, given we already cover the key ones.
I could add the pre/post (affix) one, but not sure how useful that is, given how can just directly add the content in the buffer.
See #302; cc @andras-simonyi (both because related to previous discussion of activate processors, and because you might have input on my note below)

add org-cite citation editing commands

---

README.org
oc-bibtex-actions.el

This adds a simple configurable activate processor, that includes a 
small function to attach a keymap to org citations.
------------------------------
This uses the oc-basic activate processor, but adds a keymap function, adapted from org-ref-cite, to enable using keybindings to edit citations at point.
But it's also configurable, so if you want to use this for basic fontification and preview instead, you can do that by setting `oc-bibtex-actions-activation-functions` accordingly.
https://github.com/andras-simonyi/org-cite-csl-activate
Here's the current mapping:
```console
key             binding
---             -------
C-d             oc-bibtex-actions-delete-citation
C-k             oc-bibtex-actions-kill-citation
S-<left>        oc-bibtex-actions-shift-reference-left
S-<right> …
```

Add activate processor

---

README.org
oc-bibtex-actions.el

This allows left-click for bibtex-actions-dwim and right-click for embark-act.

feat(oc): add mouse keybindings

---

bibtex-actions.el
oc-bibtex-actions.el

Move the function to bibtex-actions.el, and use it to describe all
bibtex-actions keymaps.

refactor: move/generalize describe-keymap function

---

citar-org.el

Since all the required functions are now autoloaded (#342), we can also autoload the call to `org-cite-register-processor` (protected by `with-eval-after-load 'oc`). This will register the `citar` processor whenever org-cite is loaded, but will not load `citar-org` until:
* the `org-cite-{activate,follow,insert}-processor` variables have been set to `'citar`, and
* an Org-mode file is loaded and org-cite is activated, a citation is followed, or `org-cite-insert` is called.
The usage instructions are then simply "install citar" and "set the `org-cite-*-processor` variables to `'citar`". There is no need to arrange for `citar-org` to be loaded explicitly, which can pull in all of Org Mode if done too early, or can result in the org-cite processor not being registered if done too late.

Autoload the call to org-cite-register-processor

---

citar-filenotify.el
citar.el

We can't rely on the calls to `citar-file--normalize-paths` in the default values for the `citar-bibliography` defcustom, since those will be overridden by the user. Instead, normalize the paths where needed in the code.
The same applies to the defcustoms for `citar-{library,notes}-paths`; these are always used in contexts where no normalization is needed.
Fixes #351
PS: This bug is also fixed in @aikrahguzar's [branch](https://github.com/aikrahguzar/bibtex-actions/blob/ecb3df00ff3e9c68d5f41771b0587865f200ad9c/bibtex-actions.el#L316).

fix: normalize bibliography file paths where needed

---

README.org
citar.el

Set up the Embark integration automatically when Citar is loaded, and also add it to the autoload file. This means that Embark and Citar can be loaded in any order, and neither will pull in the other. Citar will be loaded the first time its target finder is invoked by `embark-act`.
There seems to be some redundancy between the embark action maps for `citar` and `citar-org`. Currently, loading `citar-org` overrides the action map for `bib-reference` targets, from `citar-map` to `citar-buffer-map`. This is of course, not ideal, and perhaps both of these action maps should be merged.
This PR also includes the simplified use-package stanza for `citar-org` made possible by #353, allowing its loading to be deferred to the last possible moment (fixes #340).

Autoload keymaps required for embark and simplify readme

---

README.org
citar-file.el
citar-latex.el
citar-markdown.el
citar-org.el
citar.el

Another big step to removing the bibtex-completion dependency.
- add a new major-mode "adapter" design
- add citar-latex and citar-markdown based on above
- move around code and rename symbols accordingly
- rewrite citar-insert-keys, citar-insert-citation
- replace bibtex-completion-at-point with citar-keys-at-point
@aikrahguzar did most of this work.
------
TODO:
1. [X] docs
2. [X] deprecate "add"/"attach" pdf commands 
3. [X] move org-cite target finder to `citar-org`, adjust [code](https://github.com/bdarcus/citar/blob/62a6ca420fb39b6f64a3b54ab415c9dd67a404b0/citar.el#L672)
4. [ ] change `citar-major-mode-function` from using `major-mode` to `derived-mode-p` (but I'm not sure how to do that with this code ATM; may defer to this to a later PR)
5. [ ] test
-------
Given how much #307 has …

add citar-latex, citar-markdown

---

citar-file.el
citar.el

Three commits:
1. a new completing-read-based `citar-select-ref` to complement the existing one.
2. changing `citar-open-entry` to use 1.
3. bugfix for notes function
I bundle the first two here in part to see how well 1 will work with embark.
Turns out: well.
cc @roshanshariff - WDYT?

feat: completing-read citar-select-ref option

---

citar-filenotify.el

Debugging why my cache wasn’t correctly invalidated, the previous pcase patterns didn’t seem to work at all. I’m constantly confused by pcase however, so I’m not sure if this is the best way, but it seems to work correctly.

Fix pcase use in citar-filenotify

---

README.org
citar-latex.el
citar-org.el
citar.el

Fix #246.
Also fix #367.
-----
Per suggestion at https://github.com/bdarcus/citar/issues/246#issuecomment-961584996, this should do it @minad @roshanshariff.
The only issue is the `citar--insert-entry` function doesn't work correctly.
Any ideas?
I could just remove that entirely, and instead use embark for that?

remove bibtex-completion dependency

---

citar-org.el
citar.el

This change is questionable. I know that you dislike that the general Embark
actions are always there since they clutter which-key. Unfortunately without
this change Embark is badly broken. We need at least the C-h=embark-keymap-help
action. Furthermore in the minibuffer we would still like to have the
keybindings for embark-export/collect-snapshot etc.

Install embark general maps as parent keymap

---

README.org
citar-org.el
citar.el

For Org-only usage, it is no longer necessary to set `citar-bibliography`, just `org-cite-global-bibliography`.  To make this possible, `citar-org-local-bibs` now includes the contents of `org-cite-global-bibliography`. With this change, no Citar-specific configuration is required in Org mode.
Fixes #364.

Update citar-org configuration in README.org

---

citar.el

With commit ec0695ba (PR #374), the citar keymaps are no longer autoloaded and therefore cannot be referred to by the autoloaded `with-eval-after-load` form for embark. This causes an error at emacs initialization.
This change splits the embark `with-eval-after-load` into two parts: the first is autoloaded and adds the target finder, while the second deals with the keymaps. This should be fine because embark will never need the citar keymaps unless it has (1) run the citar target finder, or (2) been invoked from a citar command.

Fix embark autoloads

---

README.org

The current configuration causes issues when `use-package-always-ensure` or `straight-use-package-by-default` are enabled, because they assume that `citar-org` is a separate package.  Instead, just go with `use-package citar`.
Also remove the `:after org` directive.  Instead use the `:package` argument to `:bind` to defer the modification of `org-mode-map` until after `org` is loaded.
Fixes #380.

Simplify use-package block for Org-mode usage (fixes #380)

---

citar-markdown.el

This commit aims to fix a problem with the current version of `citar-markdown-key-at-point`, which is that it returns the closing bracket with the last citekey of a given markdown citation, such that `[@Smith2012]` returns `Smith2012]` in the Embark indicator.
Before resorting to `thing-at-point`, I tried editing the `split-string` regex in final line of the current code, to include a closing bracket, like so: `(cadr (split-string str "[]@;]")))))`. This nicely trimmed the closing bracket from the returned string.
But for reasons I don't understand, that change wreaked some strange havoc, leading Embark to recognize anything between brackets as a markdown citation. Not a great outcome.
I had some tinker experience with `thing-at-point`, so voila, an attempt at a bugfix. Interested to know …

Use thing-at-point for citar-markdown-key-at-point

---

README.org

I can't tell if the screenshot really shows vertico, but the link and the link description don't match up. So one of these should be corrected.

Correct link to vertico

---

citar-file.el

Change to use 'split-string', as it's more clear to me.
Fix #398

fix(file): misparsing of jabref file fields

---

citar-file.el
citar.el

Partial implementation* of the `bibtex-completion-find-additional-pdfs` feature, from `bibtex-completion`.
Allows `citar-file` functions to find files that begin with a citekey and end with an extension listed in `citar-file-extensions`, with any amount (or kind) of text between.
Example: Citar currently finds only "Smith2012.pdf"; with this commit it will also find "Smith2012 - John Smith - Title of Example Book, Vol. 1 (2012).pdf."
*I say "partial implementation" because in `bibtex-completion` this feature is enabled by setting a defcustom to 't'. That's certainly an option, if desirable.

Add support for finding files with expanded naming convention

---

citar-file.el
citar-org.el

Fix #412.
Also, autoload citar-org-open-notes-default.
-----
@roshanshariff @localauthor - can you two confirm this change is fine?
Basically, the function change (suggested by @roshanshariff?) filtered the list of possible names to ensure the files were present, which is not the purpose of it (checking if a file is present should happen elsewhere). 
So I simply removed the filter.
But I don't now how this will interact with the new extended search functionality. Will this cause a problem with open-notes, for example, when creating a new note?
EDIT: seems not:
```elisp
ELISP> (let ((citar-file-find-additional-files nil))(citar-file--get-note-filename "t1" citar-notes-paths '("org")))
(("/home/bruce/org/roam/biblio/t1.org" . new))
ELISP> (let ((citar-file-find-additional-files …
```

fix(file): remove filter on possible-names

---

citar-file.el
citar.el

This replaces the 'citar-add-pdf-attachment' wrapper with a new function.
Close #422.
------
@xcapaldi - I'll take a closer look tomorrow before merging. 
If you'd like me to credit you on the commit, I need the email address to use.

Add 'citar-attach-library-files'

---

test/install.el

A few updates for the test script, including some that were needed to get it to run:
- Install other package dependencies: `parsebib` and `s`
- Update `load-path` so that requires in `citar.el` are handled
- Update location of tmp directly in message
- Add `embark-act` binding (facilitate testing embark with citar)

Updates for test script

---

README.org
citar-latex.el
citar-markdown.el
citar-org.el
citar.el

This is a continuation of #394.
- Context-aware insert-citation
- Context-aware insert/edit function
- Target finders for keys and citations
Partly implements #383: in Markdown, `citar-insert-citation` will now add new keys after the current citation key, or at the beginning of the citation if point is just after `[`.
Fixes #278, fixes #393: `citar-insert-citation` now does something useful in Org mode, either inserting a new org-cite citation or adding new keys to an existing citation at point. The new keys are added at the beginning of the citation if point is before the first key, or after the current key otherwise.
Relevant to #203: there are now two target finders, one for individual keys and the other for full citations. Both target types have the same keymap, offering the usual …

Context-sensitive insertion and edit commands

---

citar-filenotify.el
citar.el

Combining these commits, for convenience.
The first two seem uncontroversial: remove a duplicate function and include `citar-file-note-extensions` in `citar-open`. 
The third and fourth might be handled differently:
The third adds a "No associated file" message to `citar--library-files-action`, for cases where there is no associated file.
The fourth adds a "Key not found" message to `citar-select-ref/s`, which is returned if one of the many citar-open functions (open, library-files, notes, link, entry) is invoked at-point on a key that is malformed or simply not in the bibliography. Currently in this case these functions return an unhelpful error ("Wrong type argument: stringp, nil") because `citar-select-refs` has passed them `nil`.

Minor edits

---

README.org
citar-org.el
citar.el

Enhance note functionality.
- Split open-note into open and format functions defcustoms
- Simplify and enhance default org note format function
Also fix #420.
-------------------
Remaining questions/issues:
1. [X] hook up defcustom
2. [X] should the note template get its own defcustom? I think not ATM.
3. [X] do these changes break org-roam-bibtex integration? If yes (almost certainly the case), fix.
3. [X] need to adjust open-note
2. [X] should I move the remaining mode-specific details (like `#+title`) from template to function? I tend to think not.
3. [X] doc update
On org-roam-bibtex, see the key [orb-edit-note function](https://github.com/org-roam/org-roam-bibtex/blob/d65b70e9d19efc5001e01a61c36cc3e57e198131/org-roam-bibtex.el#L584), which …

feat(org): add separate format-note function

---

citar-org.el

Without this, user will get an error if opening outside of org.

fix: autoload 'citar-org-format-note-default'

---

citar-markdown.el
citar-org.el
citar.el

Adds `citar-export-buffer-citations-to-file` as suggested in issue #459, @pemocarlo.
Also adds `citar-markdown-list-keys`.
EDIT: (see comment below)
~~Currently only available `latex-mode` and `markdown-mode`.~~
~~Support for `org-mode` would require a function that lists all org-citations in buffer, which is more than I can undertake at this point.~~
Thoughts on function name? Other issues?

Add citar-export-buffer-citations-to-file

---

citar-file.el
citar-org.el
citar.el

Implements the changes discussed in #456:
Split the functionality of `citar-file--possible-names` into two new functions:
- `citar-file--parse-file-field` to extract file names from an entry field
- `citar-file--directory-files` to find files in directories whose names start with keys.
Change `citar-file--files-for-entry`, `citar-file--files-for-multiple-entries`, and `citar-file--get-note-filename` to use these functions.
Add the function `citar-file--has-file-p`, which scans the relevant directories once and returns a predicate for the existence of associated files. Use this function in `citar--format-candidates` to efficiently add "has:files" and "has:notes" indicators.
With this implementation, the "has:file" indicator can be incorrect when `citar-file-find-additional-files` is set to …

citar-file.el: Refactor file-finding functions

---

citar-latex.el
citar.el

Sets bibtex-dialect before running functions from bibtex.el

fix: citar--insert-bibtex and citar-export-local-bib-file

---

citar-citeproc.el
citar.el

In response to https://github.com/bdarcus/citar/issues/448#issuecomment-981833659 and in light of #245.
This refactors the handling of references to better facilitate the addition of `citar-copy-reference`.
- `citar-insert-reference-function` is now `citar-format-reference-function`
- `citar--insert-reference` is now `citar--format-reference`
The function set in `citar-format-reference-function` must return formatted references as a string, which is either inserted by `citar-insert-reference` or added to the kill-ring by `citar-copy-reference`.
To consider:
- What do you think about the way `citar--format-reference` formats multiple references (ie, no spacing b/t references; refs not sorted)? This is how `citar--insert-reference` worked too, but maybe now is a good time to tweak things, …

Refactor reference functions, add citar-copy-reference, citar-citeproc

---

citar-citeproc.el
citar.el

Expand commentary in citar-citeproc.el
- Clarify instructions for use
- Add info about CSL style and locale files
Allow 'citar-citeproc-csl-style' to be set to filename only, not full path
- This requires the file to be located in 'citar-citeproc-csl-styles-dir'
- Full path also accepted
Add changes suggested by roshanshariff in #455

Clarify citar-citeproc settings and minor adjustments

---

citar-markdown.el

Use re-search-forward instead of string-match on buffer-string.
Improves performance up to 15x in testing.

Optimize citar-markdown-list-keys

---

citar-markdown.el

Correctly handle Pandoc citation keys with braces:
- In `@{Foo_Bar}:`, the citation key is `Foo_Bar`, not `{Foo_Bar}:`
- Also respect Pandoc's punctuation rule: in `@Foo_bar.baz.`, the citation key is `Foo_bar.baz`.
See https://pandoc.org/MANUAL.html#citation-syntax for more examples.

citar-markdown-list-keys: Use `citar-markdown-citation-key-regexp`

---

citar-latex.el
citar.el

Here's a draft PR to get started with, fixing #452. I've only implemented LaTeX support so far. Some notes:
Basically what we're doing is having a variable which controls whether to prompt for a citation style, and then the behaviour that variable controls is inverted by a prefix arg. The only entry point is `citar-insert-citation`, so it'll be that commands prefix arg that controls things. There are thus two approaches:
1) have a single variable (e.g. `'citar-prompt-for-cite-style`), do the inversion logic with in `citar-insert-citation`, then pass the result to the specific major mode functions as an argument which tells them whether or not to prompt. They don't need to worry about handling prefix args or doing logic with the variable. This has the advantage that there is only one …

Default citation style

---

citar-file.el
citar.el

For example, this can be used to select a reference that has a note:
``` emacs-lisp
(citar-select-ref :filter (citar-make-note-predicate))
```
or to select a reference that has an associated file:
``` emacs-lisp
(citar-select-ref :filter (citar-make-file-predicate))
```
or to select a reference that has a "keywords" field containing "ethics":
```emacs-lisp
(citar-select-ref :filter (lambda (_key entry)
(when-let ((keywords (assoc-default "keywords" entry)))
(string-match-p "ethics" keywords))))
```
Also simplify and update documentation for functions in `citar-file.el`
Closes #272.

Add :filter argument to `citar-select-ref`

---

citar-citeproc.el
citar-file.el
citar.el

Introduces the following naming convention for function arguments:
- KEYS-ENTRIES is a list whose elements are either KEY or (KEY . ENTRY) pairs.
- KEY-ENTRY-ALIST is a list whose elements are (KEY . ENTRY) pairs
- KEYS is a list whose elements are keys.
The existing function `citar--extract-keys` will transform KEYS-ENTRIES into KEYS.
The new function `citar--ensure-entries` will transform KEYS or KEYS-ENTRIES into a KEY-ENTRY-ALIST.
Almost all the user-facing Citar commands (and the non-interactive function `citar-run-default-action`) take KEYS-ENTRIES arguments and have been added to `embark-multitarget-actions`. These arguments are transformed into `KEY-ENTRY-ALIST` in the few places that need them.
Note: I've tested all the functions in as many conditions as I could think of, but …

Add support for Embark multi-actions

---

citar.el

When nil, all citar commands will use `completing-read` instead of `completing-read-multiple`.
Closes #492

Add `citar-select-multiple` option

---

citar-markdown.el

When calling `citar-insert-citation` with a prefix argument, the meaning of `citar-markdown-prompt-for-extra-arguments` is now inverted.
Fixes #499.

Add invert-prompt argument to citar-markdown-insert-citation

---

README.org

Since this is not a dependency anymore

docs: remove references to bibtex-completion

---

citar.el

This is incomplete, but is a branch to test the ideas in #495, which you should do in conjunction with 'embark-act-all'. The devil will be in the details here.
There are two categories of commands in citar:
That is, which take a single reference candidate, and do something with it. With `embark-act-all`, the command would be run once per reference.
All of the "open" commands fit here. This and #491 updates these to use CR instead of CRM. 
That is, which ideally take a list of reference candidates and do something with them as one action. With `embark-act-all`, the command would be run once, on the list of references.
Many of the "insert" (notably `citar-insert-citation`) and "copy" (`citar-copy-reference`) commands fit in this category, as does the …

refactor: crm -> cr

---

citar.el

The 'citar--library-files-action' function had incorrect logic.
Also rename to singular `citar--library-file-action`.
Fix #505

fix: incorrect conditional logic

---

citar.el

Adds a major-mode check to `citar-insert-citation`
Fixes #441
~Adds a defvar `citar-major-modes`; a list of currently supported major modes. (This list could be made programatically, but that seemed like overkill.)~
Adds "No associated resource" message to `citar-open`, sidestepping a "Wrong type argument" error.

Add error handling to citar-insert-citation and citar-open

---

README.org

The current org-cite example doesn't seem to work for me unless I set `citar-bibliography` (I get "Make sure to set citar-bibliography" if I try to insert a citation). This change just updates the readme to set this variable.

Update README to also set citar-bibliography

---

citar.el

Biblatex prefers 'journaltitle' to 'journal', and at least prior to Emacs 28, `bibtex.el` wouldn't even recognize 'journal' as an alias for 'journaltitle' if you had `bibtex-dialect` set to `biblatex`. This small change is just to reflect the fact that many entries biblatex is happy with lack a 'journal' field but have a 'journaltitle' field.

Update default value of `citar-templates`

---

citar.el

Incorporates into the new 'citar-open-multi' a fix from #460, #465
Issue:
- when using citar-open, notes are not distinguished from files, and are therefore opened with 'citar-file-open-function'
- when 'citar-file-open-function' is set to 'citar-file-open-external', notes are opened by the system, which takes some time to find emacs
- presumably notes should be opened in emacs directly, using find-file; previously discussed in #465
Fix:
'citar-multi-open' checks directory of selection against 'citar-notes-paths'

Fix citar-open-multi to open notes with find-file

---

citar.el

Closes #544
When citar-open-prompt is t, the default, citar-open will prompt for resource
selection even when there is only one resource. When nil, single resources
will open immediately, without any prompt.

Add option for citar-open to forego selection prompt

---

README.org

The previously stated default value in the README would make citar choke, since it didn't include `preview`. So I'm just updating this to reflect the actual default value.

Add preview template to README

---

README.org

The minimal configuration code example in the `README.org` missing a closing bracket `)`.
This causes an `End of file during parsing` error if the code example is copy-pasted into the Emacs config.

Fix minimal configuration example

---

citar.el

Include "crossref" in the default value of `citar-additional-fields`, to make use of `parsebib`'s ability to make use of crossref information.

Change default value of `citar-additional-fields`

---

README.org
citar-file.el

With this PR, citar will associate BibTeX entries that have a 'crossref' field with the resources (files, notes, links) associated with the cross-referenced entry.
For example: consider an entry for "Baym1965" that has a 'crossref' field "Meyers1999". When `citar-open` is called and "Baym1965" is selected, the minibuffer will list all files, notes, and links associated with both "Baym1965" and "Meyers1999".
The proper prefixes, denoting an associated file, note, or link, will also be listed with each candidate in the minibuffer.
So far, all the permutations I could think of seem to work as expected.
NOTE: One considerable wrinkle of the BibTeX crossref feature is that an entry with the 'crossref' field must come _before_ the cross-referenced entry in the bib file. So, in the example …

Add file support for BibTeX 'crossref' field

---

citar-org.el

Split out one function to flatten list, and have
citar-org--style-candidates only handle the styling.

refactor(oc): split style candidates function

---

citar-org.el

This defcustom is no longer needed.
Fix #557

remove citar-file-note-org-include

---

citar-org.el

Prefix arg wasn't properly accounted for.
Fix #574

Fix spurious content in citar-org-insert-citation

---

citar.el

Hi, thank you for your work on this great package.
Does this use of `browse-url-default-browser` come with some intention?
If not, I think `browse-url` is better because:
- it's consistent with other codes. `citar-open` and `citar-open-multi` use it.
- `browse-url-default-browser` doesn't care about `browse-url-browser-function` that users can set. This is actually a problem for me.

Use browse-url instead of browse-url-default-browser

---

README.org
citar-file.el

The newer Zotero style file entries have the format:
`file = {Li and Samulski 2020 - Engineering adeno-associated virus
vectors for gene therapy:files/1491/Li and Samulski 2020 - Engineering
adeno-associated virus vectors for gene therapy.pdf:application/pdf}`
This allows `citar-file-parser-default` to find the associated files
correctly.
Closes #578.

Find files in : or ; delimited file entries.

---

citar-citeproc.el

fix: citar-citeproc-format-reference, for local-bibs

---

citar.el

Currently, this PR has two commits, both to facilitate programmatic filtering etc of candidates.
First, when creating candidates, it adds cons cells for files or notes, I can drop this commit if we prefer the more general solution below, but I don't believe the operations here (pushing cons to a list) are expensive.
```elisp
(("has-note" . t) ; this PR adds this and next line
("has-file" . t)
("doi" . "10.1111/j.1540-6040.2009.01269.x")
("journaltitle" . "City \\& Community")
("date" . "2009-03-01")
("author" . "Zukin, Sharon and Trujillo, Valerie and Frase, Peter and Jackson, Danielle and Recuber, Tim and Walker, Abraham")
("title" . "New Retail Capital and Neighborhood Change: Boutiques and Gentrification in {{New York City}}")
("=type=" . "article")
("=key=" . "zukin2009"))
``` 
To …

Add file/note data to candidates

---

citar-citeproc.el
citar-file.el
citar-latex.el
citar-org.el
citar.el

If you object to these changes after they are merged (for example, think certain functions should be public), please file an issue with your request(s), and link to this.
The last two are the most important:
1. salutis' suggestions https://github.com/bdarcus/citar/issues/438#issuecomment-1001245176
2. related, I guess private variables should also have `--`? If yes, fix that too.
3. ~Should we rename the predicate functions to end with `-p`, per elisp convention, and actually keep them public (`citar-has-note-p`)?~ (no; they aren't predicate functions exactly)
4. ~Is `citar-has-a-value` function a predicate function? It sounds like it, but docstring says no. Maybe it should be something like `citar-field-with-value`?~ 
5. ~Am I correct we're inconsistently using `ITEM` and `ENTRY` to …

API cleanup

---

README.org
citar-file.el
citar.el

This PR attempts to answer two questions:
1. How would we #518?
2. How, in doing so, would that include ensuring that the citar UI correctly updates the status of "has notes" display, when multiple bib notes may be contained within a single file?
So it adds a `citar-keys-with-notes-functions` defcustom, with the idea that, for example, a `citar-org-roam` package could provide a function to query the org-roam db, and provide that list of keys.
```elisp
(defun citar-org-roam--keys-with-note ()
"Return a list of keys with associated note(s)."
(mapcar #'car (org-roam-db-query
[:select ref :from refs :where (= type "cite")])))
```
And of course, that it could provide an "open-function" to have org-roam handle that.
Finally, it also, per suggestion from @roshanshariff, turns the `open-notes` …

Generalize note API

---

README.org

As discussed in #613, this commit fixes the fallback in `citar--open-notes` and updates the README to add the note for needing `:immediate-finish t` in ORB capture notes.
Cheers.

fix for issue 613

---

citar.el

Mostly from my minor annoyance at seeing reftex flood my messages buffer. Moves the check to after the candidates have been computed. Should be a bit faster too.

Don't compute `(citar--local-files-to-cache)` unless necessary.

---

.dir-locals.el
Eldev
Makefile

Would something like this be useful, @roshanshariff, that in time we could hook up to the CI, including unit tests, etc?
Right now, all that works is `make lint`, where it will flag a ton of things, mostly code formatting/indenting.
I had an earlier github actions setup (code still here), but I found it too interventionist.
This would reject PRs (in the sense mark them needing fixes) with these warning though.
But my thought is in the interim, could add it and ask contributors to use it? I know it would be useful for me!

Add start of eldev linting, etc.

---

citar.el

Since this is only needed for notes, rename accordingly.
Also, strip the properties, since annotation functions work on plain strings.

Rename note annotator, strip properties

---

Makefile
citar-cache.el
citar-capf.el
citar-citeproc.el
citar-embark.el
citar-file.el
citar-format.el
citar-latex.el
citar-markdown.el
citar-org.el
citar.el
test/citar-file-test.el
test/citar-test.el

I was realizing I was making too many small commits, so setup this branch to collect various commits to get this repo ready for tagging 1.0 in the next week or so.
The first commit emerged out of a suggestion from the MELPA review for citar-embark, and that is to use these for the file headers:
https://spdx.dev/ids/
So I've done that, and also removed the human-readable license text. I hope that's OK; I guess it should be if MELPA folks recommended it.
@localauthor and @aikrahguzar - not sure if you wanted your names on the copyright for some of these files?
-------------
1. I'm not sure on this, but on the note API, I'm leaning towards only defining the `:action` function (or we could all it `:open`?), and leaving out the `:create` one. My reasoning is that creating new notes is pretty …

pre-1.0-cleanup branch

---

citar-cache.el
citar-embark.el
citar-file.el
citar-format.el
citar.el

This PR continues #658.
Both these functions now offer to create notes for the chosen keys. The customization variable `citar-open-always-create-note` controls whether the "create" option is offered only for keys that don't already have notes. Regardless of this variable's value, the `citar-create-note` command can always be used to create multiple notes for any key, if supported by the `citar-note-source`.
This new feature is implemented as an extra option to `citar--select-resource`, which has now learned about the `create-note` pseudo-resource type. The `citar-open-notes` and `citar--open-resource` functions also learned to create new notes.
There is a new command called `citar-open-note`, which prompts to select a note from all the available notes and opens it. It can also be called …

Improve note creation functionality (and tweak API)

---

citar.el

Parsebib now handles removing TeX markup, so we remove it.
See also #668

Remove citar--clean-string

---

citar-latex.el
citar.el

Fixes part of #662 related to auto-loading. 
Also fixes an edge case for the multiple selection. Now on deselection we just restore the history to what it was before instead of trying to remove the topmost element from the history.

Fix autoload issue + multiple selection corner case

---

README.org
citar-cache.el
citar-file.el

The new customization variable `citar-file-open-functions` is an alist from file extensions to functions used to open them. `citar-file-open` will now use this variable to decide how to open library files.
Fixes #507

Make `citar-file-open` use customizable functions to open files

---

citar.el

I'm planning to merge this and then tag 1.0 "very soon"; ideally once Joost has a chance to improve performance of #659 a bit, and I can bump parsebib to 4.3 instead.
If any last minute changes, @roshanshariff, you can add them here, though I think we're good.
Edit: seeing your latest message, can also hold off until the weekend if you prefer. Just want to get this off my TODO list in the next few days.
If you do want to add a more substantial commit, you can also just do that, and I can then rebase on main.

v1.0 last call

---

citar-org.el

Any reason not to do this?
It allows ` citar-org-key-at-point` to read `@key` strings in property drawers as citekeys (org won't recognize citations in property drawers), and so for `embark-act` etc to work on them.
It does not, however, work with `org-open-at-point`.
I guess one open question is what the allowed syntax there should be? I chose this because org-roam supports (for indexing), and because it avoids confusion about what's an org citation.
Close #684
cc @pprevos

Add at-point function for org property drawers

---

citar-file.el
test/citar-file-test.el

When encountering a filename with backslashes, consider both the original and unescaped versions.
Should fix #693.

Unescape filenames in citar-file--parser-default

---

citar.el

citar--completion-table mistakenly called the completion system's predicate on the minibuffer input typed by the user instead of calling it on the completion candidate, a display string for a reference.

Call predicate on candidate display string (fix #708)

---

.github/workflows/check.yml
Eldev

Make sure the Github CI workflow installs all needed dependencies in the separate "prepare" step, before the subsequent compile/test/lint steps. This was already the case for the declared package dependencies, but not for the additional build/test/lint dependences (auctex and embark) listed in the Eldev file.
Otherwise, when Eldev installs packages, it seems to delay adding already-installed packages to the Emacs load path. Org mode does not like this; the built-in version of Org gets loaded before the updated version from GNU ELPA, causing "Org version mismatch" errors.
Also update Eldev according to the suggestions of "eldev doctor"; make the Eldev file byte-compilable, use melpa instead of melpa-unstable, and use gnu-elpa instead of just gnu.

github-ci: install all dependencies in the Eldev "prepare" step

---

README.org
citar-capf.el
citar-org.el

Fix #729
--------
I don't understand this code well, and not sure this is the best solution, but it seems to work.
Here's the definition of `cl--set-buffer-substring`:
```elisp
(defun cl--set-buffer-substring (start end val)
(save-excursion (delete-region start end)
(goto-char start)
(insert val)
val))
```
Note: I uncovered a bug in the shift function that preceded this. If you try to move right, for example, when point is on the last reference, you will get a type error.
I think either it should do nothing but not trigger an obscure error, or move it to be the first reference.
I have implemented the former, but added a more useful error message.
Finally, I also added `citar-capf-setup` here.

Don't use setf with buffer-substring

---

.github/workflows/check.yml
citar.el

Add an optional TRUNCATE and ANDSTR args for this function.
Addresses #694
-------
Is this output all correct?
```elisp
ELISP> (citar--shorten-names "Doe, J and Smith, N and Jones, K and Lamb, H")
"Doe, Smith, Jones, Lamb"
ELISP> (citar--shorten-names "Doe, J and Smith, N and Jones, K and Lamb, H" 3)
"Doe, Smith, Jones et al"
ELISP> (citar--shorten-names "Doe, J and Smith, N and Jones, K and Lamb, H" 3 "and")
"Doe, Smith and Jones et al"
```

Add formatting options for citar--shorten-names

---

.github/workflows/check.yml
README.org
citar-format.el
citar.el

Modify:
* `citar-display-transform-functions` so it becomes a list of shortcuts to include in template specs (like `"${author:20%etal}"` where `etal` is the key that then points to a list of a function symbol and optional arguments).
* `citar-get-display-value` so it allows an optional transform function
* `citar-format--parse` to include transform list
* formatting functions to properly integrate the above
Close #694
-----
This is an alternative to #734; I think easier to implement and configure, and more flexible.
I think it all works, and **unless I hear otherwise, I'll likely merge it tomorrow, March 13**.
EDIT: I got sidetracked by a stupid variable declaration bug; now fixed.
@andersjohansson @pprevos - any feedback on this? I think you were, or may be, interested in such a feature. …

Allow transform modifiers in templates

---

citar-citeproc.el

While not needed for the interactive function, can be useful for other uses to be able to specify a CSL style when running it.
So this adds an optional argument for that.
Close #737

citar-citeproc-format-reference: Add style arg

---

citar-cache.el
citar-citeproc.el

Can you take a look at this @andras-simonyi @andersjohansson?
It's a simple solution to the problem we've previously discussed, and an alternative to #710. I mostly stole code from `org-cite-csl-activate`!
But this should:
1. fix #702
2. provide all the advantages of using the citar cache
3. remove the potential limitation noted in the `org-cite-csl-activate` [README](https://github.com/andras-simonyi/org-cite-csl-activate#using-the-citar-cache-for-retrieving-bibliographic-entries).
The only problem I can potentially see is _maybe_ it slows down initial loading of libraries a little, and uses a bit more memory. But I doubt it's a significant impact. And if it ever were, we could always add a defcustom so people could turn it off?
@andras-simonyi - not sure what you think about this, but …

Don't throw out field data; use cache for citeproc

---

README.org
citar.el

The separating colon was missing.

Fix typo in templates with %etal

---

citar-citeproc.el

I think these are minimally-invasive changes to address a few little issues with this module; mostly what happens if a user is new to all this, and hasn't set up any CSL locales or styles directories.
Close: #746

misc fixes/improvements for citeproc

---

README.org
citar.el
test/manual/citar.el

* add `padding` to `citar-indicator`, set to default value of 1
* incorporate into `citar--make-indicator-symbols`
* deprecate `citar-symbol-separator`
* update README
Close: #759
---------------
I think I fixed it.
So basically, there's no longer a global variable for the separator; instead it's defined in the `citar-indicator` specs, with a default of 1.
If you two can either test, or at least check the basic logic, that'd be great.
@gwbrck @robmoss
Hmm .. as I look at documentation, this seems a bit odd:
```elisp
:symbolwidth 2
:emptysymbol "  "
```
The latter is required, because one might want to use an icon also.
But maybe they should be consistent? Probably not, since they serve different purposes?

fix(indicators): add `padding` slot

---

README.org
citar.el

@andersjohansson - can you give this a try? 
It's just a few lines (no cache or hash table), but works for me.
```elisp
(defun citar-is-cited ()
"Return function to check if reference is cited in buffer."
(let ((iscited
(citar--major-mode-function 'list-keys #'ignore)))
(lambda (citekey)
(member citekey iscited))))
```
My test file was small though.
If this is good to go, I can merge it.
I gave co-author credit on the commit :-)
We can then later think of other enhancements as and if needed (like possibly extending `'list-keys` beyond the immediate buffer, or optimizing performance).
PS - `'list-keys` was originally added to allow exporting of local bib files.

feat(indicators): add cited

---

citar-org.el

To resolve #607 and #606. The following pull request does the following:
1. Renames `citar-org-update-pre-suffix` to `citar-org-update-prefix-suffix`. I found the initial naming potentially misleading. This rename may increase the discoverability of the command.
2. Adds a helper function, `citar-org--update-prefix-suffix`.
3. (Unchanged) When on a reference, will prompt for a new prefix and suffix, with default values being their current values.
4. (New) When on a citation (but not a reference), will prompt for a new prefix and suffix **for every reference in the citation at point** from left to right.
5. (New) When on a reference and called with prefix arg, does the same as (4).
6. (New) There will always be *only one space* between citekey and citation suffix, unless there is no …

Upgrade citar-org-update-pre-suffix to iterate through all references in citation

---

citar-org.el

The current behavior for `citar-org-shift-reference-left` and `citar-org-shift-reference-right` fails when, in the same citation, there are multiple references with the same citekey (regardless of prefix and suffix differences). The reason for this lies in `citar-org--get-ref-index` using citekeys to retrieve the index of a reference within a citation.
This pull request has that function use the point at the beginning of a reference instead. Doing so required a slight change to how `citar-org--shift-reference` leaves the point on the correct reference.
Finally, the final commit enhances how the point is left on the reference: rather than left at the beginning, the point retains its position relative to where the command was called in the reference. For instance, if the command was called …

Fix edge case for `citar-org-shift-reference-{left,right}`

---

citar-format.el
test/citar-format-test.el

Add some tests for template parsing.
Fixes #809

fix(citar-format): correctly handle star field widths in templates

---

citar-citeproc.el

Since `list` is a list of cons cells, to get the name of the csl style when `list` has one element `caar` needs to be used; `car` returns the cons cell itself.

Fix bug in `citar-citeproc-select-csl-style`

---

citar.el

Hopefully, not *too* controversial a change but I find that I use this binding a lot, especially when cleaning up my references.

citar-map: add `citar-add-file-to-library' to "a"

---

citar-file.el
citar.el

feat: enable recursive library paths

---

citar-file.el
citar.el

I jumped the gun on the original recursive directories PR; it was incomplete. This PR fixes that.

Fix recursive directories

---

README.org
citar-org.el

As described in #842, citar uses the built-in `org-cite-basic-activate` which can cause significant slowdowns. This PR defines our own activate function, `citar-org-cite-basic-activate`, and uses it by default (replaces `org-cite-basic-active` in `citar-org-activation-functions`). This new activate function is identical to the built-in basic activate function but uses citar functions to speed up the expensive operations of the built-in activate function.

Use a more performant org-cite activate processor by default

---

citar-org.el

In Emacs 31, org-element-property and org-element-type have moved to a new file: org-element-ast.
Update code to handle this properly.
PS - closed #847 in favor of this because I made a git mistake and didn't want to fix it.

fix(org): update load, declare-function

---

README.org
citar-latex.el

Don't make reftex do a rescan everytime
